### ISSUE TITLE
Where do I type my char?

### ISSUE THREAD

**Issue by germanattanasio** [jzhang300/char-by-char#1]

**Comment by simondebbarma** [comment]
We are still setting up the system for this.

Our initial idea was to create something like Reddit Place but for code instead. 

One option was to create an application where we allow users to log in and insert one character to the code with a 24-hour interval. This seems to be the most rational and practical representation of the idea.

Now, when James and I discussed this idea, we also tried to understand how long it would take to build anything if a user gets to put a character only once a day. That's an insane amount of time. We joked that a millennium later, humans (or, robots or any other form of conscience) would still be adding code to this repo to complete it. 

I don't know how much momentum this repo will receive, but until then, we are keeping it as simple as possible. Please help us figure this out further by joining other discussions here.

**Comment by jzhang300** [comment]
@germanattanasio let's just start with `app.js` for now.  I believe we're trying to import react first.  We're kind of just figuring out as we go along.
